from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage
from pydantic import BaseModel, Field
from typing import List
from core.config import get_settings

settings = get_settings()

class PlanOutput(BaseModel):
    """Structured plan generated by the LLM."""
    steps: List[dict] = Field(description="A sequential list of steps to accomplish the goal.")

def plan_node(state: dict):
    """
    The Planner Agent:
    Takes the user goal and breaks it down into actionable tool-calling steps.
    """
    print(f"--> Planner Node processing input: {state['user_input']}")
    
    # In a real app we'd inject memory context here
    
    # Mocking planner for immediate testability during hackathon setup
    mock_plan = [
        {
            "id": 1,
            "action": "Understand user goal",
            "tool_name": "none",
            "tool_input": {},
            "completed": False
        },
        {
            "id": 2,
            "action": "Execute required tool if any",
            "tool_name": "mock_tool",
            "tool_input": {"query": state['user_input']},
            "completed": False
        }
    ]
    
    return {
        "plan": mock_plan,
        "actions_taken": [{"agent": "planner", "action": "created_plan"}]
    }

def should_execute_next(state: dict) -> str:
    """Routing logic: determine if there's a step to run, or if we are done."""
    plan = state.get("plan", [])
    if not plan:
        return "synthesize"
        
    for step in plan:
        if not step.get("completed"):
            return "executor"
            
    return "synthesize"
